version: '1.0'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: markassist-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://dinesh1234:dinesh1234@cluster1ppmarking.atlefpe.mongodb.net/
      - DB_NAME=test
      - API_KEY=AIzaSyAijhFV9Y2hKxOfZsikHfQyXPE-eSRwKZg
      - AUTH_DOMAIN=papermarkin.firebaseapp.com
      - PROJECT_ID=papermarkin
      - STORAGE_BUCKET=papermarkin.appspot.com
      - MESSAGING_SENDER_ID=529261970661
      - APP_ID=1:529261970661:web:7b9e613f7d71e0cf1d800c
      - MEASUREMENT_ID=G-852GDJS8LT
      - OPENAI_API_KEY=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
      - AZURE_API_KEY=1a0eabe69a514bada1badecefe5266ab
      - AZURE_ENDPOINT=https://markassist.cognitiveservices.azure.com/
    networks:
      - markassist
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: ["npm", "start"]
    container_name: markassist-react-client
    ports:
      - "3000:3000"
    networks:
        - markassist
volumes:
  db:
networks:
    markassist:
        driver: bridge

